2025-05-25 03:32:15.694 UTC | INFO     | apscheduler.scheduler     | Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-05-25 03:32:15.694 UTC | INFO     | apscheduler.scheduler     | Added job "refresh_active_mission_cache" to job store "default"
2025-05-25 03:32:15.694 UTC | INFO     | apscheduler.scheduler     | Scheduler started
2025-05-25 03:32:15.694 UTC | INFO     | app.app                   | APScheduler started for background cache refresh.
2025-05-25 03:32:15.694 UTC | INFO     | app.app                   | BACKGROUND TASK: Starting proactive cache refresh for active real-time missions.
2025-05-25 03:32:15.694 UTC | INFO     | app.app                   | BACKGROUND TASK: Proactive cache refresh for active real-time missions completed.
2025-05-25 03:32:18.817 UTC | INFO     | app.app                   | Attempting remote load for power (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.826 UTC | INFO     | app.app                   | Attempting remote load for ctd (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.842 UTC | INFO     | app.app                   | Attempting remote load for weather (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.858 UTC | INFO     | app.app                   | Attempting remote load for waves (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.870 UTC | INFO     | app.app                   | Attempting remote load for vr2c (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.884 UTC | INFO     | app.app                   | Attempting remote load for solar (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.898 UTC | INFO     | app.app                   | Attempting remote load for fluorometer (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.908 UTC | INFO     | app.app                   | Attempting remote load for ais (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:18.920 UTC | INFO     | app.app                   | Attempting remote load for errors (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:19.040 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for errors (m204). Will try next path.
2025-05-25 03:32:19.040 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for solar (m204). Will try next path.
2025-05-25 03:32:19.040 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for fluorometer (m204). Will try next path.
2025-05-25 03:32:19.040 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for waves (m204). Will try next path.
2025-05-25 03:32:19.040 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for ctd (m204). Will try next path.
2025-05-25 03:32:19.047 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for weather (m204). Will try next path.
2025-05-25 03:32:19.047 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for power (m204). Will try next path.
2025-05-25 03:32:19.047 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for vr2c (m204). Will try next path.
2025-05-25 03:32:19.054 UTC | INFO     | app.app                   | Attempting remote load for errors (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.063 UTC | INFO     | app.app                   | Attempting remote load for solar (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.073 UTC | INFO     | app.app                   | Attempting remote load for fluorometer (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.084 UTC | INFO     | app.app                   | Attempting remote load for waves (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.096 UTC | INFO     | app.app                   | Attempting remote load for ctd (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.114 UTC | INFO     | app.app                   | Attempting remote load for weather (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.126 UTC | INFO     | app.app                   | Attempting remote load for power (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.138 UTC | INFO     | app.app                   | Attempting remote load for vr2c (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.147 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for ais (m204). Will try next path.
2025-05-25 03:32:19.157 UTC | INFO     | app.app                   | Attempting remote load for ais (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:19.280 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for power (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Amps%20Power%20Summary%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.280 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for vr2c (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Vemco%20VR2c%20Status.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.281 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for fluorometer (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Fluorometer%20Samples%202.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.281 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for ctd (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Seabird%20CTD%20Records%20with%20D.O..csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.281 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for waves (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/GPS%20Waves%20Sensor%20Data.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.281 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for errors (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Vehicle%20Error%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.281 UTC | WARNING  | app.app                   | No usable remote data found for power (m204). Falling back to default local.
2025-05-25 03:32:19.283 UTC | INFO     | app.app                   | Attempting fallback local load for power (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.290 UTC | INFO     | app.app                   | CACHE STORE: Storing power for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.290 UTC | WARNING  | app.app                   | No usable remote data found for vr2c (m204). Falling back to default local.
2025-05-25 03:32:19.290 UTC | INFO     | app.app                   | Attempting fallback local load for vr2c (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.293 UTC | INFO     | app.app                   | CACHE STORE: Storing vr2c for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.293 UTC | WARNING  | app.app                   | No usable remote data found for fluorometer (m204). Falling back to default local.
2025-05-25 03:32:19.293 UTC | INFO     | app.app                   | Attempting fallback local load for fluorometer (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.351 UTC | INFO     | app.app                   | CACHE STORE: Storing fluorometer for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.351 UTC | WARNING  | app.app                   | No usable remote data found for ctd (m204). Falling back to default local.
2025-05-25 03:32:19.351 UTC | INFO     | app.app                   | Attempting fallback local load for ctd (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.480 UTC | INFO     | app.app                   | CACHE STORE: Storing ctd for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.480 UTC | WARNING  | app.app                   | No usable remote data found for waves (m204). Falling back to default local.
2025-05-25 03:32:19.480 UTC | INFO     | app.app                   | Attempting fallback local load for waves (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.487 UTC | INFO     | app.app                   | CACHE STORE: Storing waves for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.487 UTC | WARNING  | app.app                   | No usable remote data found for errors (m204). Falling back to default local.
2025-05-25 03:32:19.487 UTC | INFO     | app.app                   | Attempting fallback local load for errors (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.492 UTC | INFO     | app.app                   | CACHE STORE: Storing errors for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.492 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for weather (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Weather%20Records%202.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.492 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for solar (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Amps%20Solar%20Input%20Port%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.492 UTC | WARNING  | app.app                   | No usable remote data found for weather (m204). Falling back to default local.
2025-05-25 03:32:19.492 UTC | INFO     | app.app                   | Attempting fallback local load for weather (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.513 UTC | INFO     | app.app                   | CACHE STORE: Storing weather for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.513 UTC | WARNING  | app.app                   | No usable remote data found for solar (m204). Falling back to default local.
2025-05-25 03:32:19.513 UTC | INFO     | app.app                   | Attempting fallback local load for solar (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.526 UTC | INFO     | app.app                   | CACHE STORE: Storing solar for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.528 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for ais (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/AIS%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:19.528 UTC | WARNING  | app.app                   | No usable remote data found for ais (m204). Falling back to default local.
2025-05-25 03:32:19.528 UTC | INFO     | app.app                   | Attempting fallback local load for ais (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:19.540 UTC | INFO     | app.app                   | CACHE STORE: Storing ais for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:19.554 UTC | INFO     | app.core.summaries        | PowerSummaryDebug: Initial battery_wh = 1373.14980812389, type = <class 'numpy.float64'>
2025-05-25 03:32:19.554 UTC | INFO     | app.core.summaries        | PowerSummaryDebug: Condition met for battery_wh = 1373.14980812389
2025-05-25 03:32:19.554 UTC | INFO     | app.core.summaries        | PowerSummaryDebug: Calculated battery_percentage = 49.482875968428466
2025-05-25 03:32:19.770 UTC | INFO     | app.core.processors       | VR2C Preprocessing: Initial df columns: ['timeStamp', 'latitude', 'longitude', 'status String']
2025-05-25 03:32:19.874 UTC | INFO     | app.core.processors       | VR2C Preprocessing: Parsed data from 'status String' (first 5 rows):
  SerialNumber  DetectionCount  PingCount
0       407014              30       2073
1       407014              30       8002
2       407014              30      16407
3       407014              30      27390
4       407014              30      36765
2025-05-25 03:32:19.875 UTC | INFO     | app.core.processors       | VR2C Preprocessing: After to_numeric (first 5 rows of DC, PC):
DetectionCount:
0    30
1    30
2    30
3    30
4    30
Name: DetectionCount, dtype: int64
PingCount:
0     2073
1     8002
2    16407
3    27390
4    36765
Name: PingCount, dtype: int64
2025-05-25 03:32:19.881 UTC | INFO     | app.core.summaries        | VR2C Summary: df_vr2c_processed head before selecting last_row:
                  Timestamp SerialNumber  DetectionCount  PingCount
0 2025-04-21 14:07:16+00:00       407014              30       2073
1 2025-04-21 15:07:16+00:00       407014              30       8002
2 2025-04-21 16:07:16+00:00       407014              30      16407
3 2025-04-21 17:12:16+00:00       407014              30      27390
4 2025-04-21 18:12:16+00:00       407014              30      36765
2025-05-25 03:32:19.881 UTC | INFO     | app.core.summaries        | VR2C Summary: df_vr2c_processed tail before selecting last_row:
                    Timestamp SerialNumber  DetectionCount  PingCount
776 2025-05-24 09:37:16+00:00       407014             457    9578599
777 2025-05-24 10:37:16+00:00       407014             457    9587975
778 2025-05-24 11:42:16+00:00       407014             457    9601357
779 2025-05-24 12:42:16+00:00       407014             457    9609463
780 2025-05-24 13:42:16+00:00       407014             457    9619104
2025-05-25 03:32:19.881 UTC | INFO     | app.core.summaries        | VR2C Summary: last_row content:
Timestamp                                 2025-05-24 13:42:16+00:00
latitude                                                  42.422291
longitude                                                -61.340765
status String     407014,926,2025-04-15 13:42:15,STS,DC=457,PC=9...
SerialNumber                                                 407014
DetectionCount                                                  457
PingCount                                                   9619104
Name: 780, dtype: object
2025-05-25 03:32:19.881 UTC | INFO     | app.core.processors       | VR2C Preprocessing: Initial df columns: ['timeStamp', 'latitude', 'longitude', 'status String']
2025-05-25 03:32:20.033 UTC | INFO     | app.core.processors       | VR2C Preprocessing: Parsed data from 'status String' (first 5 rows):
  SerialNumber  DetectionCount  PingCount
0       407014              30       2073
1       407014              30       8002
2       407014              30      16407
3       407014              30      27390
4       407014              30      36765
2025-05-25 03:32:20.033 UTC | INFO     | app.core.processors       | VR2C Preprocessing: After to_numeric (first 5 rows of DC, PC):
DetectionCount:
0    30
1    30
2    30
3    30
4    30
Name: DetectionCount, dtype: int64
PingCount:
0     2073
1     8002
2    16407
3    27390
4    36765
Name: PingCount, dtype: int64
2025-05-25 03:32:20.041 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: Initial df columns: ['timeStamp', 'latitude', 'longitude', 'c1Avg', 'c1Gain', 'c1StdDev', 'c1Min', 'c1Max', 'c1Count', 'c2Avg', 'c2Gain', 'c2StdDev', 'c2Min', 'c2Max', 'c2Count', 'c3Avg', 'c3Gain', 'c3StdDev', 'c3Min', 'c3Max', 'c3Count', 'pressSteps', 'temp']
2025-05-25 03:32:20.047 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: df columns after rename: ['Timestamp', 'Latitude', 'Longitude', 'C1_Avg', 'c1Gain', 'c1StdDev', 'c1Min', 'c1Max', 'c1Count', 'C2_Avg', 'c2Gain', 'c2StdDev', 'c2Min', 'c2Max', 'c2Count', 'C3_Avg', 'c3Gain', 'c3StdDev', 'c3Min', 'c3Max', 'c3Count', 'pressSteps', 'Temperature_Fluor']
2025-05-25 03:32:20.049 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: After to_numeric (first 5 rows of C1_Avg, Temp):
C1_Avg:
0    19.666517
1    15.884580
2    17.677041
3    19.453796
4    17.517462
Name: C1_Avg, dtype: float64
Temperature_Fluor:
0    11.973500
1     8.800634
2     8.755884
3     6.163551
4     6.367220
Name: Temperature_Fluor, dtype: float64
2025-05-25 03:32:20.065 UTC | INFO     | app.core.summaries        | Fluorometer Summary: df_fluorometer_processed head before selecting last_row:
                  Timestamp     C1_Avg       C2_Avg     C3_Avg  Temperature_Fluor
0 2025-04-21 14:07:55+00:00  19.666517  1554.659601  13.306993          11.973500
1 2025-04-21 14:11:33+00:00  15.884580  1170.224059  14.291912           8.800634
2 2025-04-21 14:15:11+00:00  17.677041  1337.907450  13.609628           8.755884
3 2025-04-21 14:27:58+00:00  19.453796  1223.692250  11.838050           6.163551
4 2025-04-21 14:31:36+00:00  17.517462  1407.775877  13.437804           6.367220
2025-05-25 03:32:20.070 UTC | INFO     | app.core.summaries        | Fluorometer Summary: df_fluorometer_processed tail before selecting last_row:
                     Timestamp     C1_Avg      C2_Avg    C3_Avg  Temperature_Fluor
9837 2025-05-23 16:50:50+00:00  97.221997  172.036054  7.110716           1.026134
9838 2025-05-23 16:54:07+00:00  82.115135  218.350409  6.339864           1.268597
9839 2025-05-23 17:01:42+00:00  90.099906  177.216638  6.633368           1.164002
9840 2025-05-23 17:04:58+00:00  76.271700  179.305370  6.799408           1.347577
9841 2025-05-23 17:08:14+00:00  66.401624  203.445416  7.443270           1.042872
2025-05-25 03:32:20.070 UTC | INFO     | app.core.summaries        | Fluorometer Summary: last_row content:
Timestamp            2025-05-23 17:08:14+00:00
Latitude                             43.696822
Longitude                           -71.089695
C1_Avg                               66.401624
c1Gain                               92.521642
c1StdDev                             26.151546
c1Min                                  48.3512
c1Max                               198.753349
c1Count                               93.09797
C2_Avg                              203.445416
c2Gain                               96.562493
c2StdDev                              2.293903
c2Min                               209.772721
c2Max                               178.468278
c2Count                              88.594258
C3_Avg                                 7.44327
c3Gain                              112.858768
c3StdDev                              1.459103
c3Min                                 3.502694
c3Max                                12.012886
c3Count                              91.975214
pressSteps                                 0.0
Temperature_Fluor                     1.042872
Name: 9841, dtype: object
2025-05-25 03:32:20.070 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: Initial df columns: ['timeStamp', 'latitude', 'longitude', 'c1Avg', 'c1Gain', 'c1StdDev', 'c1Min', 'c1Max', 'c1Count', 'c2Avg', 'c2Gain', 'c2StdDev', 'c2Min', 'c2Max', 'c2Count', 'c3Avg', 'c3Gain', 'c3StdDev', 'c3Min', 'c3Max', 'c3Count', 'pressSteps', 'temp']
2025-05-25 03:32:20.082 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: df columns after rename: ['Timestamp', 'Latitude', 'Longitude', 'C1_Avg', 'c1Gain', 'c1StdDev', 'c1Min', 'c1Max', 'c1Count', 'C2_Avg', 'c2Gain', 'c2StdDev', 'c2Min', 'c2Max', 'c2Count', 'C3_Avg', 'c3Gain', 'c3StdDev', 'c3Min', 'c3Max', 'c3Count', 'pressSteps', 'Temperature_Fluor']
2025-05-25 03:32:20.082 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: After to_numeric (first 5 rows of C1_Avg, Temp):
C1_Avg:
0    19.666517
1    15.884580
2    17.677041
3    19.453796
4    17.517462
Name: C1_Avg, dtype: float64
Temperature_Fluor:
0    11.973500
1     8.800634
2     8.755884
3     6.163551
4     6.367220
Name: Temperature_Fluor, dtype: float64
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | --- Debugging Template Context ---
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Type of power_info: <class 'dict'>
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Keys in power_info: ['values', 'latest_timestamp_str', 'time_ago_str', 'mini_trend']
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Type of power_info['values']: <class 'dict'>
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Keys in power_info['values']: ['BatteryWattHours', 'SolarInputWatts', 'BatteryPercentage', 'PowerDrawWatts', 'NetPowerWatts', 'Panel1Power', 'Panel2Power', 'Panel4Power', 'Timestamp']
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | --- Debugging VR2C Info ---
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Type of vr2c_info: <class 'dict'>
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Keys in vr2c_info: ['values', 'latest_timestamp_str', 'time_ago_str', 'mini_trend']
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Type of vr2c_info['values']: <class 'dict'>
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Content of vr2c_info['values']: {'SerialNumber': '407014', 'DetectionCount': np.int64(457), 'PingCount': np.int64(9619104), 'Timestamp': '2025-05-24 13:42:16 UTC'}
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | --- Debugging Fluorometer Info ---
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Type of fluorometer_info: <class 'dict'>
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Keys in fluorometer_info: ['values', 'latest_timestamp_str', 'time_ago_str', 'mini_trend']
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Type of fluorometer_info['values']: <class 'dict'>
2025-05-25 03:32:20.111 UTC | INFO     | app.app                   | Content of fluorometer_info['values']: {'C1_Avg': np.float64(66.40162416660965), 'C2_Avg': np.float64(203.44541618322472), 'C3_Avg': np.float64(7.443270110988674), 'Temperature_Fluor': np.float64(1.0428719133571127), 'Latitude': np.float64(43.6968215784555), 'Longitude': np.float64(-71.08969511628281), 'Timestamp': '2025-05-23 17:08:14 UTC'}
2025-05-25 03:32:21.015 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for ctd (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.041 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for weather (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.052 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for fluorometer (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.055 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: Initial df columns: ['timeStamp', 'latitude', 'longitude', 'c1Avg', 'c1Gain', 'c1StdDev', 'c1Min', 'c1Max', 'c1Count', 'c2Avg', 'c2Gain', 'c2StdDev', 'c2Min', 'c2Max', 'c2Count', 'c3Avg', 'c3Gain', 'c3StdDev', 'c3Min', 'c3Max', 'c3Count', 'pressSteps', 'temp']
2025-05-25 03:32:21.063 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: df columns after rename: ['Timestamp', 'Latitude', 'Longitude', 'C1_Avg', 'c1Gain', 'c1StdDev', 'c1Min', 'c1Max', 'c1Count', 'C2_Avg', 'c2Gain', 'c2StdDev', 'c2Min', 'c2Max', 'c2Count', 'C3_Avg', 'c3Gain', 'c3StdDev', 'c3Min', 'c3Max', 'c3Count', 'pressSteps', 'Temperature_Fluor']
2025-05-25 03:32:21.064 UTC | INFO     | app.core.processors       | Fluorometer Preprocessing: After to_numeric (first 5 rows of C1_Avg, Temp):
C1_Avg:
0    19.666517
1    15.884580
2    17.677041
3    19.453796
4    17.517462
Name: C1_Avg, dtype: float64
Temperature_Fluor:
0    11.973500
1     8.800634
2     8.755884
3     6.163551
4     6.367220
Name: Temperature_Fluor, dtype: float64
2025-05-25 03:32:21.076 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for vr2c (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.076 UTC | INFO     | app.core.processors       | VR2C Preprocessing: Initial df columns: ['timeStamp', 'latitude', 'longitude', 'status String']
2025-05-25 03:32:21.199 UTC | INFO     | app.core.processors       | VR2C Preprocessing: Parsed data from 'status String' (first 5 rows):
  SerialNumber  DetectionCount  PingCount
0       407014              30       2073
1       407014              30       8002
2       407014              30      16407
3       407014              30      27390
4       407014              30      36765
2025-05-25 03:32:21.199 UTC | INFO     | app.core.processors       | VR2C Preprocessing: After to_numeric (first 5 rows of DC, PC):
DetectionCount:
0    30
1    30
2    30
3    30
4    30
Name: DetectionCount, dtype: int64
PingCount:
0     2073
1     8002
2    16407
3    27390
4    36765
Name: PingCount, dtype: int64
2025-05-25 03:32:21.208 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for waves (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.220 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for power (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.236 UTC | INFO     | app.app                   | Latitude/Longitude not provided for forecast. Attempting to infer from telemetry for mission m204.
2025-05-25 03:32:21.250 UTC | INFO     | app.app                   | Attempting remote load for telemetry (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-25 03:32:21.250 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for solar (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-25 03:32:21.428 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for telemetry (m204). Will try next path.
2025-05-25 03:32:21.436 UTC | INFO     | app.app                   | Attempting remote load for telemetry (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-25 03:32:21.528 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for telemetry (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Telemetry%206%20Report%20by%20WGMS%20Datetime.csv'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:21.529 UTC | WARNING  | app.app                   | No usable remote data found for telemetry (m204). Falling back to default local.
2025-05-25 03:32:21.529 UTC | INFO     | app.app                   | Attempting fallback local load for telemetry (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-25 03:32:21.569 UTC | INFO     | app.app                   | CACHE STORE: Storing telemetry for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-25 03:32:21.582 UTC | INFO     | app.app                   | Inferred location for mission m204: Lat=44.47753281138516, Lon=-63.39545485439191
2025-05-25 03:32:21.582 UTC | INFO     | app.core.forecast         | Attempting to fetch marine forecast from: https://api.open-meteo.com/v1/marine
2025-05-25 03:32:22.569 UTC | WARNING  | app.core.forecast         | HTTPStatusError when fetching https://api.open-meteo.com/v1/marine: 404 - Client error '404 Not Found' for url 'https://api.open-meteo.com/v1/marine?latitude=44.47753281138516&longitude=-63.39545485439191&hourly=wave_height%2Cwave_direction%2Cwave_period%2Cwindspeed_10m%2Cwinddirection_10m%2Cocean_current_velocity%2Cocean_current_direction%2Cweathercode%2Ctemperature_2m%2Cprecipitation&timezone=GMT'
For more information check: https://httpstatuses.com/404
2025-05-25 03:32:22.570 UTC | WARNING  | app.core.forecast         | Marine forecast API returned 404 for lat=44.47753281138516, lon=-63.39545485439191. Falling back to general forecast.
2025-05-25 03:32:22.570 UTC | INFO     | app.core.forecast         | Attempting to fetch general forecast from: https://api.open-meteo.com/v1/forecast
2025-05-25 03:33:07.650 UTC | INFO     | app.app                   | APScheduler shut down.
2025-05-25 03:33:07.650 UTC | INFO     | apscheduler.scheduler     | Scheduler has been shut down
